//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_management_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_borrowed
    {
        public Book_borrowed()
        {
            this.pay_fines = new HashSet<pay_fines>();
        }
    
        public int brBook_ID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> Borrower_ID { get; set; }
        public Nullable<System.DateTime> brBook_date { get; set; }
        public Nullable<System.DateTime> expected_return { get; set; }
        public Nullable<System.DateTime> return_date { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Borrower Borrower { get; set; }
        public virtual ICollection<pay_fines> pay_fines { get; set; }
    }
}
