//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_management_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.Book_borrowed = new HashSet<Book_borrowed>();
        }
    
        public int BookID { get; set; }
        public string ISBN { get; set; }
        public string title { get; set; }
        public string author { get; set; }
        public Nullable<int> edition { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> BookState_number { get; set; }
    
        public virtual ICollection<Book_borrowed> Book_borrowed { get; set; }
        public virtual StateBook StateBook { get; set; }
    }
}
