//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_management_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class pay_fines
    {
        public int fines_ID { get; set; }
        public Nullable<int> brBook_ID { get; set; }
        public Nullable<int> delay_days { get; set; }
        public Nullable<double> payment { get; set; }
        public Nullable<int> fines_number { get; set; }
    
        public virtual Book_borrowed Book_borrowed { get; set; }
        public virtual fines_category fines_category { get; set; }
    }
}
