//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_management_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateBook
    {
        public StateBook()
        {
            this.Book = new HashSet<Book>();
        }
    
        public int bookState_number { get; set; }
        public string book_state { get; set; }
    
        public virtual ICollection<Book> Book { get; set; }
    }
}
